apiVersion: v1
kind: Pod
metadata:
  name: command-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["/bin/sh", "-c"]    # 명령어 설정
      args: ["echo 'Hello, Kubernetes!' && env"]
  restartPolicy: Never   # 컨테이너 종료 후, 재기동 방지 설정 

