apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webtob
  name: webtob
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  initContainers:
  - image: busybox
    name: busybox
    command: ["bin/sh", "-c"]
    args:
    - cp /data/http.m /home/webtob/config/http.m;
      cp /data/mime.types /home/webtob/config/mime.types;
    volumeMounts:
    - name: webtob-config-path
      mountPath: /home/webtob/config
    - name: webtob-config
      mountPath: /data
  containers:
  - image: josunghwan/webtob_5.0.0.4:b324
    name: webtob
    volumeMounts:
    - name: webtob-config-path
      mountPath: /home/webtob/config
  volumes:
  - name: webtob-config
    configMap:
      name: cm-webtob
  - name: webtob-config-path
    emptyDir: {}

