apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-sc-pvc
spec:
  nodeSelector:
    kubernetes.io/hostname: k8sedu-node01
  containers:
  - image: nginx
    name: nginx-sc-pvc
    volumeMounts:
    - name: pv-storage
      mountPath: /opt
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pvc-sc-test

