apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sc-test
spec:
  capacity:
    storage: 2G
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8sedu-node01]}

