apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx03
    type: web-server
  name: nginx03-service-cluster
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx03
    type: web-server
  type: ClusterIP  
