apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: env-sample
  name: env-sample
spec:
  containers:
  - image: josunghwan/env_sample:v01
    name: test
    env:
    - name: SAMPLE
      value: sample test value
  dnsPolicy: ClusterFirst
  restartPolicy: Never

