apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  namespace: default
data:  # Value에 Base64로 인코딩한 값을 넣어줘야 한다.
  DB_NAME: c2FtcGxl   # sample의 Base64값
  DB_PASSWORD: cGFzc3dvcmQ=   # password의 Base64값
