apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: env-secret-pod01
  name: env-secret-pod01
spec:
  containers:
  - image: josunghwan/env_sample:v01	 	  
    name: test
    envFrom:	    # envFrom 설정
    - secretRef:
        name: env-secret  
  dnsPolicy: ClusterFirst
  restartPolicy: Never

