apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: env-secret-pod02
  name: env-secret-pod02
spec:
  containers:
  - image: josunghwan/env_sample:v01	 	  
    name: test
    env:
    - name: TEST_PASSWORD  # 환경 변수 Key 값 설정
      valueFrom:
        secretKeyRef:              # 환경 변수 Value 값 설정  
          name: env-secret
          key: DB_PASSWORD   # 해당 Key의 Value값 가져온다.
  dnsPolicy: ClusterFirst
  restartPolicy: Never

