apiVersion: v1
kind: Pod
metadata:
  labels:
    app: env-secret-pod03
  name: env-secret-pod03
spec:  
  containers:
    - image: josunghwan/env_sample:v01
      name: test
      volumeMounts:
        - name: secret-path
          mountPath: /home/secret  # 파일 생성 경로
  volumes: 
     - name: secret-path
       secret:
         secretName: secret-db

