apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-hostpath
spec:
  nodeSelector:
    kubernetes.io/hostname: k8sedu-node01
  containers:
  - image: nginx
    name: nginx-hostpath
    volumeMounts:
    - name: node-dir
      mountPath: /opt
  volumes:
  - name: node-dir
    hostPath:
      path: /test
      type: DirectoryOrCreate

