apiVersion: v1
kind: ResourceQuota
metadata:
  name: space-quota
  namespace: space
spec:
  hard:
    pods: "10"                     # 최대 10개의 Pod만 생성 가능
    requests.cpu: "2"               # 전체 CPU 요청 합이 2코어 이하로 제한
    requests.memory: "8Gi"          # 전체 메모리 요청 합이 8Gi 이하로 제한
    limits.cpu: "8"                 # 전체 CPU 상한 8코어
    limits.memory: "16Gi"           # 전체 메모리 상한 16Gi
    persistentvolumeclaims: "5"     # PVC 최대 5개
    requests.storage: "100Gi"       # 최대 100Gi 스토리지 요청 가능
