apiVersion: v1
kind: Pod
metadata:
  name: security-pod
spec:
  securityContext:    # Pod 전체에 적용
    runAsUser: 1000      # UID 1000 사용자로 실행
    runAsGroup: 3000    # GID 3000 그룹으로 실행
    fsGroup: 2000         # 볼륨 파일 소유자 GID 설정
  containers:
  - name: security-container
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:	      # 특정 컨테이너에 적용
      allowPrivilegeEscalation: false     # 권한 상승 방지
      readOnlyRootFilesystem: true     # 루트 파일 시스템 읽기 전용
      capabilities:
        drop:
        - ALL   # 모든 추가 권한 제거
