apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx01
    type: web-server
  name: nginx01-service-nodeport
spec:
  ports:
  - nodePort: 30100
    port: 80
    targetPort: 80
  selector:
    app: nginx01
    type: web-server
  type: NodePort
