apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: default
rules:
- apiGroups: [""]      # Pod 컨트롤 권한 부여
  resources: ["pods"]
  verbs: ["list", "get", "update"]
  resourceNames: ["role-test-pod"]   # 특정 Resource에서만 작업 가능하도록 설정
- apiGroups: [""]      # Configmap 생성 권한 부여
  resources: ["configmaps"]
  verbs: ["create"]
